"use client";

import {
	type CallerSlipInvitation,
	DECISION_TYPE_VALUES,
	type DecisionType,
} from "@repo/shared";
import { Badge } from "@repo/ui/components/badge";
import { Button } from "@repo/ui/components/button";
import { Card } from "@repo/ui/components/card";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@repo/ui/components/dialog";
import { Input } from "@repo/ui/components/input";
import { Label } from "@repo/ui/components/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@repo/ui/components/select";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@repo/ui/components/table";
import { Textarea } from "@repo/ui/components/textarea";
import {
	ArrowLeft,
	CheckCircle,
	Loader2,
	Pencil,
} from "@repo/ui/lib/lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { CallerSlipStatusBadge } from "@/components/caller-slips/caller-slip-status-badge";
import { useCallerSlipDetail } from "@/hooks/caller-slips/use-caller-slip-detail";
import {
	useCompleteCallerSlip,
	useRecordDecision,
} from "@/hooks/caller-slips/use-caller-slip-mutations";
import { formatDocumentSource } from "@/utils/document-helpers";

const DECISION_LABELS: Record<string, string> = {
	attend: "Attend",
	decline: "Decline",
	assign_representative: "Assign Representative",
};

function formatDecision(decision: string | null): string {
	if (!decision) return "—";
	return DECISION_LABELS[decision] ?? decision;
}

function formatDateTime(iso: string): string {
	return new Date(iso).toLocaleDateString("en-PH", {
		year: "numeric",
		month: "short",
		day: "numeric",
		hour: "numeric",
		minute: "2-digit",
	});
}

function formatDate(iso: string): string {
	return new Date(iso).toLocaleDateString("en-PH", {
		year: "numeric",
		month: "long",
		day: "numeric",
	});
}

export default function CallerSlipDetailPage() {
	const params = useParams<{ id: string }>();
	const slipId = params.id;

	const { data: slip, isLoading, error } = useCallerSlipDetail(slipId);
	const completeMutation = useCompleteCallerSlip();

	const [isCompleteDialogOpen, setIsCompleteDialogOpen] = useState(false);
	const [editingInvitation, setEditingInvitation] =
		useState<CallerSlipInvitation | null>(null);

	const isCompleted = slip?.status === "completed";

	const handleComplete = async () => {
		try {
			await completeMutation.mutateAsync({ id: slipId });
			toast.success("Caller's slip marked as completed");
			setIsCompleteDialogOpen(false);
		} catch {
			toast.error("Failed to complete caller's slip");
		}
	};

	if (isLoading) {
		return (
			<div className="flex h-64 items-center justify-center gap-2 text-muted-foreground">
				<Loader2 className="size-4 animate-spin" />
				<span>Loading caller&apos;s slip...</span>
			</div>
		);
	}

	if (error || !slip) {
		return (
			<div className="flex h-64 flex-col items-center justify-center gap-3 px-4 text-center">
				<p className="text-sm text-destructive">
					Failed to load caller&apos;s slip.
				</p>
				<Button variant="outline" asChild>
					<Link href="/caller-slips">Back to Caller&apos;s Slips</Link>
				</Button>
			</div>
		);
	}

	return (
		<div className="flex flex-col gap-6">
			{/* Header */}
			<div className="flex flex-col gap-4">
				<Button variant="ghost" size="sm" className="w-fit -ml-2" asChild>
					<Link href="/caller-slips">
						<ArrowLeft className="mr-1 size-4" />
						Back to Caller&apos;s Slips
					</Link>
				</Button>

				<div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between">
					<div className="space-y-1">
						<div className="flex items-center gap-3">
							<h1 className="text-2xl font-semibold">{slip.name}</h1>
							<CallerSlipStatusBadge
								status={slip.status as import("@repo/shared").CallerSlipStatus}
							/>
						</div>
						<p className="text-sm text-muted-foreground">
							Generated by {slip.generatedBy.fullName} •{" "}
							{formatDate(slip.createdAt)}
						</p>
					</div>

					{!isCompleted && (
						<Button
							onClick={() => setIsCompleteDialogOpen(true)}
							disabled={completeMutation.isPending}
						>
							<CheckCircle className="mr-2 size-4" />
							Mark as Completed
						</Button>
					)}
				</div>
			</div>

			{/* Invitations Table */}
			<Card className="overflow-hidden p-0">
				<div className="border-b p-4">
					<h2 className="text-lg font-semibold">
						Invitations ({slip.invitations.length})
					</h2>
				</div>
				<div className="overflow-x-auto">
					<Table>
						<TableHeader>
							<TableRow>
								<TableHead>Tracking No.</TableHead>
								<TableHead>Title / Event</TableHead>
								<TableHead>Source</TableHead>
								<TableHead>Venue</TableHead>
								<TableHead>Event Date</TableHead>
								<TableHead>Decision</TableHead>
								<TableHead>Remarks</TableHead>
								{!isCompleted && (
									<TableHead className="text-right">Actions</TableHead>
								)}
							</TableRow>
						</TableHeader>
						<TableBody>
							{slip.invitations.length === 0 ? (
								<TableRow>
									<TableCell
										colSpan={isCompleted ? 7 : 8}
										className="h-24 text-center text-muted-foreground"
									>
										No invitations in this slip.
									</TableCell>
								</TableRow>
							) : (
								slip.invitations.map((inv) => (
									<TableRow key={inv.id}>
										<TableCell className="font-mono text-xs">
											{inv.document.codeNumber}
										</TableCell>
										<TableCell className="max-w-xs">
											<p className="font-medium truncate">
												{inv.document.title}
											</p>
										</TableCell>
										<TableCell>
											{formatDocumentSource(
												inv.document.source as Parameters<
													typeof formatDocumentSource
												>[0],
											)}
										</TableCell>
										<TableCell className="max-w-48 truncate">
											{inv.eventVenue}
										</TableCell>
										<TableCell className="whitespace-nowrap text-sm">
											{formatDateTime(inv.eventStartTime)}
										</TableCell>
										<TableCell>
											{inv.vmDecision ? (
												<Badge
													variant="outline"
													className={
														inv.vmDecision === "attend"
															? "bg-green-100 border-green-300 text-green-800"
															: inv.vmDecision === "decline"
																? "bg-red-100 border-red-300 text-red-800"
																: "bg-blue-100 border-blue-300 text-blue-800"
													}
												>
													{formatDecision(inv.vmDecision)}
													{inv.vmDecision === "assign_representative" &&
														inv.representativeName && (
															<span className="ml-1 font-normal">
																({inv.representativeName})
															</span>
														)}
												</Badge>
											) : (
												<span className="text-muted-foreground">—</span>
											)}
										</TableCell>
										<TableCell className="max-w-48 truncate text-sm text-muted-foreground">
											{inv.vmDecisionRemarks ?? "—"}
										</TableCell>
										{!isCompleted && (
											<TableCell className="text-right">
												<Button
													variant="outline"
													size="sm"
													onClick={() => setEditingInvitation(inv)}
												>
													<Pencil className="mr-1 size-3" />
													Record Decision
												</Button>
											</TableCell>
										)}
									</TableRow>
								))
							)}
						</TableBody>
					</Table>
				</div>
			</Card>

			{/* Complete Confirmation Dialog */}
			<Dialog
				open={isCompleteDialogOpen}
				onOpenChange={setIsCompleteDialogOpen}
			>
				<DialogContent className="sm:max-w-md">
					<DialogHeader>
						<DialogTitle>Complete Caller&apos;s Slip</DialogTitle>
						<DialogDescription>
							Are you sure you want to mark this caller&apos;s slip as
							completed? This action cannot be undone.
						</DialogDescription>
					</DialogHeader>
					<DialogFooter>
						<Button
							variant="outline"
							onClick={() => setIsCompleteDialogOpen(false)}
							disabled={completeMutation.isPending}
						>
							Cancel
						</Button>
						<Button
							onClick={handleComplete}
							disabled={completeMutation.isPending}
						>
							{completeMutation.isPending && (
								<Loader2 className="mr-2 size-4 animate-spin" />
							)}
							Confirm
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			{/* Record Decision Dialog */}
			{editingInvitation && (
				<RecordDecisionDialog
					slipId={slipId}
					invitation={editingInvitation}
					open={Boolean(editingInvitation)}
					onOpenChange={(open) => {
						if (!open) setEditingInvitation(null);
					}}
				/>
			)}
		</div>
	);
}

/* ---------- Record Decision Dialog ---------- */

interface RecordDecisionDialogProps {
	slipId: string;
	invitation: CallerSlipInvitation;
	open: boolean;
	onOpenChange: (open: boolean) => void;
}

function RecordDecisionDialog({
	slipId,
	invitation,
	open,
	onOpenChange,
}: RecordDecisionDialogProps) {
	const recordMutation = useRecordDecision(slipId);

	const [decision, setDecision] = useState<DecisionType | "">(
		(invitation.vmDecision as DecisionType) ?? "",
	);
	const [remarks, setRemarks] = useState(invitation.vmDecisionRemarks ?? "");
	const [representative, setRepresentative] = useState(
		invitation.representativeName ?? "",
	);

	// Reset form when invitation changes
	useEffect(() => {
		setDecision((invitation.vmDecision as DecisionType) ?? "");
		setRemarks(invitation.vmDecisionRemarks ?? "");
		setRepresentative(invitation.representativeName ?? "");
	}, [invitation]);

	const isAssignRep = decision === "assign_representative";
	const canSubmit = decision !== "" && (!isAssignRep || representative.trim());

	const handleSubmit = async () => {
		if (!decision) return;

		try {
			await recordMutation.mutateAsync({
				slipId,
				invitationId: invitation.id,
				vmDecision: decision as DecisionType,
				vmDecisionRemarks: remarks.trim() || null,
				representativeName: isAssignRep ? representative.trim() : null,
			});
			toast.success("Decision recorded");
			onOpenChange(false);
		} catch {
			toast.error("Failed to record decision");
		}
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className="sm:max-w-lg">
				<DialogHeader>
					<DialogTitle>Record Decision</DialogTitle>
					<DialogDescription>
						{invitation.document.title} — {invitation.document.codeNumber}
					</DialogDescription>
				</DialogHeader>

				<div className="space-y-4 py-2">
					<div className="space-y-2">
						<Label>Event Details</Label>
						<div className="rounded-md border p-3 text-sm space-y-1">
							<p>
								<span className="text-muted-foreground">Venue:</span>{" "}
								{invitation.eventVenue}
							</p>
							<p>
								<span className="text-muted-foreground">Start:</span>{" "}
								{formatDateTime(invitation.eventStartTime)}
							</p>
							<p>
								<span className="text-muted-foreground">End:</span>{" "}
								{formatDateTime(invitation.eventEndTime)}
							</p>
						</div>
					</div>

					<div className="space-y-2">
						<Label htmlFor="vm-decision">Decision</Label>
						<Select
							value={decision}
							onValueChange={(v) => setDecision(v as DecisionType)}
						>
							<SelectTrigger className="w-full" id="vm-decision">
								<SelectValue placeholder="Select a decision" />
							</SelectTrigger>
							<SelectContent>
								{DECISION_TYPE_VALUES.map((d) => (
									<SelectItem key={d} value={d}>
										{DECISION_LABELS[d] ?? d}
									</SelectItem>
								))}
							</SelectContent>
						</Select>
					</div>

					{isAssignRep && (
						<div className="space-y-2">
							<Label htmlFor="rep-name">Representative Name</Label>
							<Input
								id="rep-name"
								value={representative}
								onChange={(e) => setRepresentative(e.target.value)}
								placeholder="Enter representative's name"
							/>
						</div>
					)}

					<div className="space-y-2">
						<Label htmlFor="decision-remarks">
							Remarks{" "}
							<span className="text-muted-foreground font-normal">
								(optional)
							</span>
						</Label>
						<Textarea
							id="decision-remarks"
							value={remarks}
							onChange={(e) => setRemarks(e.target.value)}
							placeholder="Add any notes or remarks"
							rows={3}
						/>
					</div>

					{recordMutation.error && (
						<p className="text-sm text-destructive">
							{recordMutation.error instanceof Error
								? recordMutation.error.message
								: "Failed to record decision"}
						</p>
					)}
				</div>

				<DialogFooter>
					<Button
						variant="outline"
						onClick={() => onOpenChange(false)}
						disabled={recordMutation.isPending}
					>
						Cancel
					</Button>
					<Button
						onClick={handleSubmit}
						disabled={!canSubmit || recordMutation.isPending}
					>
						{recordMutation.isPending && (
							<Loader2 className="mr-2 size-4 animate-spin" />
						)}
						Save Decision
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
