// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
	schema: "src/app/db/schema.prisma",
	migrations: {
		path: "src/app/db/migrations",
	},
	datasource: { url: process.env.DATABASE_URL },
});
