"use client";

import { CALLER_SLIP_STATUS_VALUES, type CallerSlipStatus } from "@repo/shared";
import { Button } from "@repo/ui/components/button";
import { Card } from "@repo/ui/components/card";
import { DateRangePickerField } from "@repo/ui/components/date-range-picker-field";
import { Input } from "@repo/ui/components/input";
import { PaginationControl } from "@repo/ui/components/pagination-control";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@repo/ui/components/select";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@repo/ui/components/table";
import { useDebounce } from "@repo/ui/hooks/use-debounce";
import { Loader2 } from "@repo/ui/lib/lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useCallerSlips } from "@/hooks/caller-slips/use-caller-slips";
import { useCallerSlipStore } from "@/stores/caller-slip-store";
import { CallerSlipStatusBadge } from "./caller-slip-status-badge";

const PAGE_SIZE_OPTIONS = [10, 25, 50] as const;

function formatStatus(status: string): string {
	return status.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function formatDate(dateStr: string): string {
	return new Date(dateStr).toLocaleDateString("en-PH", {
		year: "numeric",
		month: "short",
		day: "numeric",
	});
}

export function CallerSlipDataTable() {
	const router = useRouter();
	const {
		search,
		statusFilter,
		dateFrom,
		dateTo,
		page,
		limit,
		setSearch,
		setStatusFilter,
		setDateFrom,
		setDateTo,
		setPage,
		setLimit,
		clearFilters,
	} = useCallerSlipStore();

	const [searchInput, setSearchInput] = useState(search);
	const debouncedSearch = useDebounce(searchInput, 300);

	useEffect(() => {
		setSearch(debouncedSearch.trim());
	}, [debouncedSearch, setSearch]);

	const { data, isLoading, error, isPlaceholderData } = useCallerSlips();

	const items = data?.items ?? [];
	const pagination = data?.pagination ?? {
		total: 0,
		page: 1,
		limit: 10,
		totalPages: 0,
	};

	const hasActiveFilters =
		search !== "" ||
		statusFilter !== "all" ||
		dateFrom !== null ||
		dateTo !== null;

	return (
		<div className="flex flex-col gap-4">
			<div className="flex flex-col gap-1">
				<h1 className="text-2xl font-semibold">Caller Slips</h1>
				<p className="text-sm text-muted-foreground">
					Manage walk-in visitor appointments and caller decisions.
				</p>
			</div>

			<Card className="flex flex-col gap-4 p-6">
				{/* Filter Bar */}
				<div className="flex flex-wrap items-center gap-2">
					<Input
						placeholder="Search caller slips..."
						value={searchInput}
						onChange={(e) => setSearchInput(e.target.value)}
						className="w-64"
					/>

					<Select
						value={statusFilter}
						onValueChange={(v) => setStatusFilter(v as typeof statusFilter)}
					>
						<SelectTrigger className="w-40">
							<SelectValue placeholder="All Statuses" />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="all">All Statuses</SelectItem>
							{CALLER_SLIP_STATUS_VALUES.map((s) => (
								<SelectItem key={s} value={s}>
									{formatStatus(s)}
								</SelectItem>
							))}
						</SelectContent>
					</Select>

					<DateRangePickerField
						from={dateFrom}
						to={dateTo}
						onChange={(from, to) => {
							setDateFrom(from);
							setDateTo(to);
						}}
						placeholder="Date range"
						className="w-64"
					/>

					{hasActiveFilters && (
						<Button
							variant="ghost"
							size="sm"
							onClick={() => {
								clearFilters();
								setSearchInput("");
							}}
						>
							Clear Filters
						</Button>
					)}

					<div className="ml-auto flex items-center gap-2 text-sm text-muted-foreground">
						{isLoading ? (
							<Loader2 className="h-4 w-4 animate-spin" />
						) : error ? null : (
							<span>
								{pagination.total} slip{pagination.total !== 1 ? "s" : ""}
							</span>
						)}
					</div>
				</div>

				{/* Table */}
				<div className="overflow-hidden rounded-md border">
					<div className="relative">
						{isPlaceholderData && (
							<div className="absolute inset-0 z-10 bg-background/50" />
						)}

						{error ? (
							<div className="flex items-center justify-center p-8 text-destructive">
								Failed to load caller slips. Please try again.
							</div>
						) : (
							<Table>
								<TableHeader>
									<TableRow>
										<TableHead className="w-50">Name</TableHead>
										<TableHead className="w-25">Status</TableHead>
										<TableHead className="w-30">Invitations</TableHead>
										<TableHead className="w-36">Generated By</TableHead>
										<TableHead className="w-32">Date Created</TableHead>
									</TableRow>
								</TableHeader>
								<TableBody>
									{isLoading ? (
										<TableRow>
											<TableCell colSpan={5} className="text-center py-8">
												<div className="flex items-center justify-center gap-2">
													<Loader2 className="h-4 w-4 animate-spin" />
													Loading...
												</div>
											</TableCell>
										</TableRow>
									) : items.length === 0 ? (
										<TableRow>
											<TableCell
												colSpan={5}
												className="text-center py-12 text-muted-foreground"
											>
												<div className="flex flex-col items-center gap-1">
													<p className="text-sm font-medium">
														{hasActiveFilters
															? "No caller slips match your filters."
															: "No caller slips yet."}
													</p>
													<p className="text-xs">
														{hasActiveFilters
															? "Try adjusting your search or date range."
															: "New caller slips will appear here once created."}
													</p>
												</div>
											</TableCell>
										</TableRow>
									) : (
										items.map((slip) => (
											<TableRow
												key={slip.id}
												className="cursor-pointer hover:bg-muted/50"
												onClick={() => router.push(`/caller-slips/${slip.id}`)}
											>
												<TableCell className="font-medium">
													{slip.name}
												</TableCell>
												<TableCell>
													<CallerSlipStatusBadge
														status={slip.status as CallerSlipStatus}
													/>
												</TableCell>
												<TableCell>{slip.invitationCount}</TableCell>
												<TableCell>{slip.generatedBy.fullName}</TableCell>
												<TableCell>{formatDate(slip.createdAt)}</TableCell>
											</TableRow>
										))
									)}
								</TableBody>
							</Table>
						)}
					</div>

					{/* Pagination */}
					{pagination.totalPages > 1 && (
						<div className="flex items-center justify-between border-t p-4">
							<div className="flex items-center gap-2">
								<span className="text-sm text-muted-foreground">
									Rows per page:
								</span>
								<Select
									value={String(limit)}
									onValueChange={(v) => setLimit(Number(v))}
								>
									<SelectTrigger className="w-16">
										<SelectValue />
									</SelectTrigger>
									<SelectContent>
										{PAGE_SIZE_OPTIONS.map((size) => (
											<SelectItem key={size} value={String(size)}>
												{size}
											</SelectItem>
										))}
									</SelectContent>
								</Select>
							</div>

							<PaginationControl
								currentPage={page}
								totalItems={pagination.total}
								itemsPerPage={limit}
								onPageChange={setPage}
							/>
						</div>
					)}
				</div>
			</Card>
		</div>
	);
}
